FROM node:16-alpine
 
USER node

#creating an folder because if it's created with WORKDIR it'll set the ownership to root
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
#The inline chown commands will set ownership of the files you are copying from your local environment to the node user in the container.
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]